<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\Dashboard\Models\**" />
    <Content Remove="Areas\Dashboard\Models\**" />
    <EmbeddedResource Remove="Areas\Dashboard\Models\**" />
    <None Remove="Areas\Dashboard\Models\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="wwwroot\webAssets\PagesJS\SingleListing.js" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\webAssets\PagesJS\SingleListing.js" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\webAssets\PagesJS\SingleListing.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid.EntityFrameworkAdapter" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.4" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary\ClassLibrary.csproj" />
  </ItemGroup>

</Project>
